### ISSUE TITLE
bug: User Deletion Error

### ISSUE THREAD

**Issue by laurentdelosieresfactorial** [slashdevops/idp-scim-sync#104]
Hello,

In some cases, the local "State" and the AWS state are inconsistent. We stumbled upon the case where the user was deleted in AWS but not in the local State. This generated an error 404, and the synchronization was not occurring anymore :( Would it be possible to ignore this error, and force the user deletion ?

<img width="1423" alt="Screenshot 2023-04-24 at 17 13 57" src="https://user-images.githubusercontent.com/101643931/234040200-8d203ef7-cbaf-4d2f-a9db-9f2f7b2823e8.png">

Best,
L.

**Comment by christiangda** [comment]
hi @laurentdelosieresfactorial thank you for reporting this, I will create a fix for this issue.
