### ISSUE TITLE
feat: Update Lambda runtime

### ISSUE THREAD

**Issue by davidmckenzie** [slashdevops/idp-scim-sync#111]
**Is your feature request related to a problem? Please describe.**
The go1.x lambda runtime is being deprecated

**Describe the solution you'd like**
The `provided.al2` runtime should be used instead

**Describe alternatives you've considered**
I'm not aware of any better runtimes

**Additional context**
Email from Amazon:
> We are ending support for the Go 1.x runtime in AWS Lambda, in line with Amazon Linux AMI end of maintenance support on December 31, 2023 [1]. Lambda continues to support the Go programming language, using the provided.al2 runtime. Using the provided.al2 runtime offers several benefits over the go1.x runtime, including support for AWS Graviton2 processors and a streamlined implementation with a smaller deployment package and faster function invoke path. For more information, see our blog post [2].
> As described in the Lambda runtime support policy [3], end of support for language runtimes in Lambda happens in two stages. Starting December 31, 2023, Lambda will no longer apply security patches and other updates to the Go 1.x runtime used by Lambda functions, and functions using Go 1.x will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Go 1.x runtime. Starting January 30, 2024, you will no longer be able to update existing functions using the Go 1.x runtime.
> We recommend that you upgrade your existing Go 1.x functions to the provided.al2 runtime before December 31, 2023.
> End of support does not impact function execution. Your functions will continue to run. However, they will be running on an unsupported runtime which is no longer maintained or patched by the AWS Lambda team.

**Comment by buulq** [comment]
Hi @christiangda,

I deployed version 0.012 by SAM app and need to upgrade to version 0.019. Can you show me the safe way to upgrade new version? Just need to download the new verson and upload to Lambda code or re-deploy SAM app?

Thanks,

**Comment by christiangda** [comment]
Hi @buulq ,

I recommend you upgrade your current version by doing the following:
1. Backup the content of your AWS Secrets (Created with the SAM Satck) in a `safe local file`
2. Backup the group filter you have configured in the deployed SAM Template, you can see it in the AWS Lambda env variables
3. Delete the content of the AWS S3 Bucket with your current state file ( this will be recreated in the first time of the new deployment)
4. Delete the Cloudformation stack created by the SAM deployment
5. Deploy the latest version of the AWS SAM Serverless application form here: https://serverlessrepo.aws.amazon.com/applications/us-east-1/889836709304/idp-scim-sync
6. During the deployment use the Values stored in your `safe local file`

How to keep this updated
1. redeploy the https://serverlessrepo.aws.amazon.com/applications/us-east-1/889836709304/idp-scim-sync with the same `app name` filling the fields with `group filter`, and the four secrets you always stored in  `safe local file` as is explained in the `steps 1` of the previous section.

Reference: https://docs.aws.amazon.com/serverlessrepo/latest/devguide/serverlessrepo-how-to-consume-new-version.html

**Comment by buulq** [comment]
Hi @christiangda,

I successfully upgraded to version 0.0.19 by following your instructions, thanks a lot for your support.

**Comment by christiangda** [comment]
amazing @buulq , thank you very much
