### ISSUE TITLE
how to sync another attribute from GG Workspace to AWS SSO

### ISSUE THREAD

**Issue by buulq** [slashdevops/idp-scim-sync#112]
Hi team,

I want to sync some another attribute of user in GG Workspace like department to AWS SSO, can you please show me how to do this, is there any needed configuration on idp function?

Thanks,

**Comment by christiangda** [comment]
hi @buulq I will check if this is possible in the AWS SSO SCIM API because this API limit the fields we can sync

**Comment by christiangda** [comment]
@buulq checking this https://docs.aws.amazon.com/singlesignon/latest/developerguide/limitations.html , The `department` is supported, so let me try to implement that for the next coming release.

**Comment by buulq** [comment]
Thanks @christiangda  for your support, hope will get this features soon.
