### ISSUE TITLE
bug: Nested Groups causes sync to fail

### ISSUE THREAD

**Issue by mmb-davidsmith** [slashdevops/idp-scim-sync#34]
**Describe the bug**
When attempting to sync a group which contains another group as a member, the sync fails when trying to retrieve user details for that address.

When running, I get the following error:
`Error: cannot sync groups and their members: error getting users from the identity provider: idp: error getting user: 019c6y181bx7798, email: accounts@<domain>, error: google: error getting user accounts@<domain>: googleapi: Error 400: Type not supported: userKey, badRequest`

**To Reproduce**
1. Create a group which contains another group as a member
2. Attempt to sync that group to AWS.

**Expected behavior**
I would expect to have a configuration option that either expanded the group or ignored it.

**Additional context**
None

**Comment by christiangda** [comment]
@mmb-davidsmith are you using the latest version [v0.0.4](https://github.com/slashdevops/idp-scim-sync/releases/tag/v0.0.4)? and deployed from the [AWS Serverless Repository](https://serverlessrepo.aws.amazon.com/applications/us-east-1/889836709304/idp-scim-sync)

**Comment by christiangda** [comment]
@mmb-davidsmith ok, thanks.  I remember having implemented some mechanism to log a warning message about `groups inside group` so, looks like this is not working properly, I will check to close this.

As part of that, I will see to create a feature request to see how to implement groups inside groups from the Identity Provider side.

**Comment by mmb-davidsmith** [comment]
Google does have a mechanism to expand groups when you make the API request. It is the 'includeDerivedMembership' field.

**Comment by christiangda** [comment]
thank you @mmb-davidsmith for this information.  I created feature request #35 to support nested groups, but before that, I'll try to fix the current problem handling the error when nested groups exist in Google Workspace.

**Comment by christiangda** [comment]
@mmb-davidsmith I fixed this bug implementing the support for `nested groups` in `Google Workspace` via PRR #36
