### ISSUE TITLE
bug: Suspended Google users synced as Enabled

### ISSUE THREAD

**Issue by aleshav** [slashdevops/idp-scim-sync#40]
First of all many thanks for your work!

**Describe the bug**
Users suspended in Google Workspace are synced to AWS SSO as Enabled

**To Reproduce**
1. Create user in Google Workspace
2. Suspend the new user
3. Sync users to AWS SSO
4. Observe: Suspended user gets synced as a normal enabled user

**Expected behavior**
User either (preferred) gets synced as "disabled" (this is how ssosync works) or alternatively does not get synced at all (and gets removed if exists)

**Comment by christiangda** [comment]
@aleshav I'll check this, during my tests this was working, so let me recheck to be sure according to your steps

**Comment by christiangda** [comment]
@aleshav I validated this one and the bug exists, I'm working to fix this
