### ISSUE TITLE
feat: Support for AWS profiles

### ISSUE THREAD

**Issue by aleshav** [slashdevops/idp-scim-sync#41]
For the idpscim to be able to connect to the S3 bucket, it seems I need to populate the following environment variables:
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- AWS_SESSION_TOKEN

Would it possible to get the credentials using profile? (e.g. using the AWS_PROFILE env var)

Thank you!

**Comment by christiangda** [comment]
@aleshav I implemented this and it is in the `master branch`, I have been testing this and it is working fine for me, also I added some comments into the file [Configuration](https://github.com/slashdevops/idp-scim-sync/blob/main/docs/Configuration.md) to understand how to use this.

Could you test this?

* Clone the project and use the `main` branch
* Create an AWS S3 Bucket
* Configure your AWS CLI Profile with access to the AWS S3 Bucket created before

__NOTE:__  this is working also if you have the `MFA enabled` in the `AWS CLI Profile`

```bash
make

export AWS_PROFILE="<your profile>" # --> required
export AWS_REGION="<your region>" # --> required
export AWS_ROLE_SESSION_NAME="idp-scim-sync" # --> not required

# execute the program
./build/idpscim \
  --aws-s3-bucket-name "<your AWS S3 bucket>" \
  --aws-s3-bucket-key "data/state.json" \
  --aws-scim-access-token "<your token>" \
  --aws-scim-endpoint "<your endpoint>" \
  --gws-service-account-file "<your service account file>" \
  --gws-user-email "<your email>" \
  --gws-groups-filter '<your filter>' \
  --sync-method 'groups'\
  --log-level info
```

Please let me know if this is working for you? to deliver this one in the next release.

**Comment by aleshav** [comment]
Hi Christian, I can confirm it is working now :-)

Thank you!
Ales
