### ISSUE TITLE
bug:  "status": "409 Conflict", not creating state file, both users and groups appeared to be synced in AWS SSO console

### ISSUE THREAD

**Issue by jchiang-genesis** [slashdevops/idp-scim-sync#45]
Hi,
       I'm sort of new to this, I've been doing the manual provisioning in AWS SSO with google workspace directory for a while. I decied to set up the auto provisioning, went through the steps with AWS Serverless Applications. After the first sync, I can see all the users and groups synced up, but all the groups are empty and and none of the users is in their groups.  I only had 2 groups (regular users and admin users), From the logs, i can see it sees the group (AWS-SSO) has 69 users. It tried to create them, but it runs into 409 conflict saying there's duplicate users already. I didn't remove all my original users and groups before turning on auto-provisioning, is that a problem? 

{
    "idp": 69,
    "level": "info",
    "msg": "reconciling users",
    "scim": 50,
    "time": "2022-02-14T17:37:21Z"
}

{
    "level": "warning",
    "msg": "creating users",
    "quantity": 23,
    "time": "2022-02-14T17:37:21Z"
}

{
    "level": "warning",
    "method": "POST",
    "msg": "aws checkHTTPResponse: body: {\"schema\":[\"urn:ietf:params:scim:api:messages:2.0:Error\"],\"detail\":\"Refused to create a new, duplicate resource.\",\"status\":\"409\",\"exceptionRequestId\":\"279ec396-441a-49f8-b1b6-a4e04c08348c\",\"timeStamp\":\"2022-02-14 17:37:21.224\"}\n",
    "status": "409 Conflict",
    "time": "2022-02-14T17:37:21Z"
}

Error: cannot sync groups and their members: error doing the first sync: error reconciling users: error creating users in SCIM Provider: scim: error creating user: aws CreateUser: error decoding response body: EOF

To reproduce the problem:
I created a new group, added a brand new user, still getting the same errors in the log, it created the group and user, but user isn't showing as part of the group members on AWS, and there's still no state file being created.

**Comment by christiangda** [comment]
@jchiang-genesis to try to understand the problem you have, please could you remove manually the state file from you S3 bucket and resync?

Remove the state file is a totally save action and it is the only way to force the reconciliation between the identity provider and scim side.

After that, please share the results without share information about your users and credentials

**Comment by christiangda** [comment]
Hi @jchiang-genesis thank you for the information

`idp-scim-sync` only `sync` `groups and their members, so I recommend to you read this document https://github.com/slashdevops/idp-scim-sync/blob/main/docs/Using-SSO.md 

apart from that, from your explanation, I can detect a corner case bug and I will validate this, let me see if I can.

**Comment by christiangda** [comment]
@jchiang-genesis I'm simulated your scenario without any success, I mean without any error, so maybe is the version of the app you have deployed.

could you deploy the latest version?

**Comment by jchiang-genesis** [comment]
Hi @christiangda , I actually just deployed it yesterday, I'm not sure where I can check the version, when i checked the deployment, below is the template version, I can try re-deploying the lambda app later again and update you here.

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  This is used to keep your AWS Single Sign-On (SSO) groups and users in sync with your
  Google Workspace directory using and AWS Lambda function.

  Project URL: https://github.com/slashdevops/idp-scim-sync
  
  
 
 As for the group membership not getting synced issue, I've attached the screenshots from both google directory and aws sso, so Jay is in AWS_Admins group on google, but not in AWS SSO. Cause I went through your demo documentation, it looks like the group membership should get synced too.  
  
![pic 2](https://user-images.githubusercontent.com/75268981/154091146-91cebc37-cb92-48ba-a93e-7ce1125b61f0.png)
![pic 3](https://user-images.githubusercontent.com/75268981/154091148-2c3ea733-155d-4a7f-96df-cb31046cc9b8.png)
![pic 1](https://user-images.githubusercontent.com/75268981/154091149-38bd464a-a50f-4ec5-aa68-92a4d0d77262.png)

**Comment by christiangda** [comment]
I will try to use this new [AWS SSO Identity Store API](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/welcome.htmll) through the [go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/identitystore/) to find a way to mitigate better this issue.

so @jchiang-genesis this is not a bug , it is a limitation in the AWS SSO SCIM API, sorry

**Comment by jchiang-genesis** [comment]
@christiangda not a problem, that's why when the reconciling users, it was showing idp has 69 and scim has 50. I did look up the issues from the old ssosync, so If i can limit to only 50 users for the first sync, it creates the state file, I can then add on more users afterwards as long as the new users won't be more than 50 users incremental?

**Comment by jchiang-genesis** [comment]
Thank you @christiangda for your help , just want to update everyone, once I cut down the group members to 48 for the initial sync, it worked as expected. But I did have to delete all my AWS SSO existing users and groups. then I was able to add back all the users.
