### ISSUE TITLE
feat: Output State file

### ISSUE THREAD

**Issue by mikejk8s** [slashdevops/idp-scim-sync#48]
Hi, awesome tool, thanks for making this. 

**Is your feature request related to a problem? Please describe.**

The initial run creates the State file at the end of its process - unfortunately if it panics before getting to the end during that first run you'll wind up with no State file inside of s3. Then if you run it again you'll just get duplicate errors. 

Unfortunately I have 100+ users in AWS now that failed to get put into groups so unless I wipe all of them it'll never be able to perform a sync in the future as it's got no clue on state so attempting to duplicate users.

**Describe the solution you'd like**
Some quick ideas I had, which may be completely off:

1. An initial empty state file is created before running the sync - so reverting to empty state would be fine 
2. Update state file throughout process and in the event it panics you'd only need to modify the last failed entry
3. Output the state to stdout or preferably a file in the directory

**Additional context**

I'm guessing this happened because I pulled in 100 users. Only 9 groups, but it panicked right after the very first user was added to a group. I've attached the panic in case you were curious. 

`➜  build git:(main) ✗ ./idpscim --config-file .idpscim.yaml 
using config file: /Users/mikej/workspace/rxrevu/idp-scim-sync/build/.idpscim.yaml
WARN[0004] no state file found in the state repository, creating this 
WARN[0004] syncing from scim service, first time syncing 
WARN[0004] reconciling the SCIM data with the Identity Provider data 
WARN[0004] creating groups                               quantity=9
WARN[0004] creating group                                group=aa-client-success
WARN[0004] creating group                                group=aa-devs
WARN[0005] creating group                                group=aa-ops
....
WARN[0006] creating users                                quantity=100
WARN[0148] joining users to groups                       quantity=3
WARN[0148] adding member to group                        email=new.user@myemail.com group=aa-client-success
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/slashdevops/idp-scim-sync/pkg/aws.(*SCIMService).GetUserByUserName(0xc0003dc040, {0x1caf0b0, 0xc0000b8000}, {0xc0005535a0, 0x10000c0006a69a8})
        /Users/mikej/workspace/corp/idp-scim-sync/pkg/aws/scim.go:303 +0x99d
github.com/slashdevops/idp-scim-sync/internal/scim.(*Provider).CreateGroupsMembers(0xc0003cea10, {0x1caf0b0, 0xc0000b8000}, 0xc0002e29f0)
        /Users/mikej/workspace/corp/idp-scim-sync/internal/scim/scim.go:413 +0x524
github.com/slashdevops/idp-scim-sync/internal/core.reconcilingGroupsMembers({0x1caf0b0, 0xc0000b8000}, {0x1cc4750, 0xc0003cea10}, 0xc0002e29f0, 0xc0002e3260)
        /Users/mikej/workspace/corp/idp-scim-sync/internal/core/reconciling.go:161 +0x18d
github.com/slashdevops/idp-scim-sync/internal/core.scimSync({0x1caf0b0, 0xc0000b8000}, {0x1cc4750, 0xc0003cea10}, 0xc000539860, 0xc000555e90, 0xc0004b0720)
        /Users/mikej/workspace/corp/idp-scim-sync/internal/core/actions.go:90 +0xb86
github.com/slashdevops/idp-scim-sync/internal/core.(*SyncService).SyncGroupsAndTheirMembers(0xc00047c900, {0x1caf0b0, 0xc0000b8000})
        /Users/mikej/workspace/corp/idp-scim-sync/internal/core/sync.go:125 +0x705
github.com/slashdevops/idp-scim-sync/cmd/idpscim/cmd.syncGroups()
        /Users/mikej/workspace/corp/idp-scim-sync/cmd/idpscim/cmd/root.go:317 +0x759
github.com/slashdevops/idp-scim-sync/cmd/idpscim/cmd.sync()
        /Users/mikej/workspace/corp/idp-scim-sync/cmd/idpscim/cmd/root.go:229 +0xa5
github.com/slashdevops/idp-scim-sync/cmd/idpscim/cmd.glob..func1(0x22acda0, {0x1b3942b, 0x2, 0x2})
        /Users/mikej/workspace/corp/idp-scim-sync/cmd/idpscim/cmd/root.go:43 +0x17
github.com/spf13/cobra.(*Command).execute(0x22acda0, {0xc0000b2190, 0x2, 0x2})
        /Users/mikej/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x22acda0)
        /Users/mikej/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/mikej/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/slashdevops/idp-scim-sync/cmd/idpscim/cmd.Execute()
        /Users/mikej/workspace/corp/idp-scim-sync/cmd/idpscim/cmd/root.go:53 +0x85
main.main()
`

**Comment by jdnurmi** [comment]
Commenting just in case you're bored - if you use identitystore, there is an existing paginated SearchUsers API call - but it's not officially supported - it's what the AWS console uses to list users, and doesn't require an arbitrary filter.

If you were to add it to your sdk's smithy definitions, and take advantage of this call, you could get more than 50 users at a shot.

For some reason, and I can only speculate, AWS has deigned it not to be official for [more than a year](https://github.com/aws/aws-sdk/issues/109).

I've used it before in as much as testing, but I'm loathe to productionalize this into any sync tool because it seems hazardous to rely on an unsupported API for such a sensitive function.

But, if one were so inclined, there is a way to make this work - even if only for that initial sync/state generation step.

**Comment by christiangda** [comment]
thanks, @jdnurmi for the information, it is amazing, looks like there is no way to get the users, groups and members (all of them > 50) we have in AWS SSO in any way.

I will try to implement this SDK first in the `idpscimcli` first to check how this work.

**Comment by christiangda** [comment]
@jdnurmi you are right, I was testing and it is impossible through the SDK either, I leave a comment in the issue you share [https://github.com/aws/aws-sdk/issues/109](https://github.com/aws/aws-sdk/issues/109#issuecomment-1059389915)

**Comment by christiangda** [comment]
hi @mikejk8s I'm reading in detail your explanation to see if your suggestion is possible to be implemented.

**Comment by christiangda** [comment]
Hi, @mikejk8s and @jdnurmi I implemented some `workaround` to avoid errors when `users and groups` already exist on `the AWS SSO side`, I'm merged in  PR #52 and I'll release that feature in the `v0.0.10`
