### ISSUE TITLE
que: Environment variable format for IDPSCIM_GWS_GROUPS_FILTER

### ISSUE THREAD

**Issue by neil-sookhoo-mission** [slashdevops/idp-scim-sync#68]
Hi there,

I successfully deployed the lambda function using the AWS Serverless Repository and was able to sync all Users and Groups into my AWS account by leaving the IDPSCIM_GWS_GROUPS_FILTER blank. 

However, I want to sync only a few Groups and my understanding is the only way to achieve this is filter all Groups except the ones I want to sync using IDPSCIM_GWS_GROUPS_FILTER. 

I tried setting this parameter but kept running into this error:
`Error: cannot sync groups and their members: error getting groups from the identity provider: idp: error listing groups: googleapi: Error 400: Invalid Input: query, invalid`

I have tried the following formats:
group1@gmail.com,group2@gmail.com,group3@gmail.com
'group1@gmail.com','group2@gmail.com','group3@gmail.com'
'group1@gmail.com','group2@gmail.com','group3@gmail.com'
"group1@gmail.com","group2@gmail.com,"group3@gmail.com"
email:group1@gmail.com,email:group2@gmail.com,email:group3@gmail.com
'email:group1@gmail.com','email:group2@gmail.com','email:group3@gmail.com'

**Comment by christiangda** [comment]
hi @neil-sookhoo-mission , maybe this can help you: https://github.com/slashdevops/idp-scim-sync/blob/main/docs/Configuration.md

```bash
...
export IDPSCIM_GWS_GROUPS_FILTER='name:AWS* email:aws*','email:administrators*'
...
```

try to use single quotes for each group.  In my case, I follow these instructions to avoid the use of too many groups: https://github.com/slashdevops/idp-scim-sync/blob/main/docs/Using-SSO.md

**Comment by christiangda** [comment]
@neil-sookhoo-mission could you validate if this is a bug or is missing information?

**Comment by neil-sookhoo-mission** [comment]
nope, all good. thanks for answering my question.
